### ISSUE TITLE
Exec Insert ERROR

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend-go#114]
when I upgrade github.com/datafuselabs/databend-go v0.5.3 to github.com/datafuselabs/databend-go v0.5.9
 scope, err := db.Begin()
        batch, err := scope.Prepare(fmt.Sprintf("INSERT INTO %s VALUES", "testd"))
        m := make([]interface{},2)
        m[0]="zzz"
        m[1]=x
        for i := 0; i < 2; i++ { 
                _, err = batch.Exec(m...)
                fmt.Println(err,i)
        }
        err = scope.Commit()
this code exec error
![企业微信截图_17151543893904](https://github.com/datafuselabs/databend-go/assets/88416508/3a64e1a0-00a3-4877-98a4-2ee5f481bdaf)

**Comment by hantmac** [comment]
Maybe there is a break change, you need to upgrade your databend version. https://github.com/datafuselabs/databend-go?tab=readme-ov-file#compatibility
