### ISSUE TITLE
upload stage  "error":{"code":"400","message":"Parse stage_name error, please check your arguments"}

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend-go#116]
stage := &godatabend.StageLocation{
                Name: "fluentbit",
                Path: fmt.Sprintf("fluentbit/%d-%s", time.Now().Unix(), filepath.Base(filename)),
        }
        fmt.Println(stage.Name)
        ctxd, cannel := context.WithCancel(context.Background())
        defer cannel()
        err = apiClient.UploadToStage(ctxd,stage, input,size)
  result:
![企业微信截图_17153298959057](https://github.com/datafuselabs/databend-go/assets/88416508/42fae100-be6c-4ee5-beed-51eb89f7349c)
![1715329918128](https://github.com/datafuselabs/databend-go/assets/88416508/2999c143-bf12-4103-94e7-d889e14857e0)
so the stage  err？ but print right name

**Comment by hantmac** [comment]
@blade83lee Try "~" stage , maybe stage name format error? 
@Xuanwo Need a help 😄

**Comment by Xuanwo** [comment]
I'm not familiar with `godatabend`. Does it add an `@` before the input stage name?

**Comment by hantmac** [comment]
Hi @blade83lee ,  you have resolved this problem?
