### ISSUE TITLE
behavior is not the same with the document

### ISSUE THREAD

**Issue by scbizu** [datafuselabs/databend-go#135]
Hi there , we tried databend-go these days to do some data migration , and I found the actual behavior is  different with the doc.

[The doc](https://docs.databend.com/sql/sql-commands/dml/dml-copy-into-table#copyoptions) says the default option of `copy into table` is `false` , but [the Go code](https://github.com/datafuselabs/databend-go/blob/main/restful.go#L79) set it to true as default.

Which side is wrong ? But the default true sounds good to me and avoids our OSS costing too much money 💰

**Comment by everpcpc** [comment]
The document you reached is from the databend server. The default `purge` option for `copy into` is false with no doubt.

But the `databend-go` driver provide a convenient way `InsertWithStage` which is a wrapper for `copy into`. It's the wrapper which sets the option to true.

**Comment by ZhiHanZ** [comment]
I think this issue is resolved, if there are anything unclear, feel free to open another issue @scbizu
