### ISSUE TITLE
Batch insert code example in document not working

### ISSUE THREAD

**Issue by washanhanzi** [datafuselabs/databend-go#72]
The document showed a not working batch insert [example](https://github.com/datafuselabs/databend-go#batch-insert)

It should be like the code in test
https://github.com/datafuselabs/databend-go/blob/0aa66ffc5c08781b2163f4d7074b0ee7928a99bc/tests/main_test.go#L104

**Comment by hantmac** [comment]
@washanhanzi Thanks for reporting. I will check it as soon as possible.
