### ISSUE TITLE
NG return 404

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend-go#88]
i use ng for databend-query
go driver SDK is 0.4.8
i use db.Exec("INSERT INTO testd VALUES('111.111.111.111',?)",x)  ,the ng return 2 logs , post and get  was success, post url and get url go to same node.
but
my code like this:
scope, err := db.Begin()
batch, err := scope.Prepare(fmt.Sprintf("INSERT INTO %s VALUES", "testd"))
for i := 0; i < 10; i++ {
, err = batch.Exec(i,x)
}
scope.Commit()
the ng return  logs  post 200  , get 404  insert failed :
1703745676.977 "10.49.2.134" 422 "POST" "10.49.2.187" "/v1/query" "" "10.49.2.187" 8000 "/v1/query" "-" "HTTP/1.1" 1557 1239 200 0.008 "-" "databend-go/0.4.2" "-" "-" "-" "-" "10.49.2.57:8000" "-" [28/Dec/2023:06:41:16 +0000]
1703745676.983 "10.49.2.134" 323 "GET" "10.49.2.187" "/v1/query/685870bc-8e5a-4098-8715-793f70d08a10/final" "_" "10.49.2.187" 8000 "/v1/query/685870bc-8e5a-4098-8715-793f70d08a10/final" "-" "HTTP/1.1" 241 118 404 0.005 "-" "databend-go/0.4.2" "-" "-" "-" "-" "10.49.2.207:8000" "-" [28/Dec/2023:06:41:16 +0000]
databend-query log  timeout 60s
the post url and get get url  not go to  same node. so is a bug?

**Comment by BohuTANG** [comment]
Ping for help from @hantmac @wubx

**Comment by blade83lee** [comment]
@hantmac

**Comment by hantmac** [comment]
> @hantmac

Thanks for reporting. I will look into it as soon as possible.

**Comment by hantmac** [comment]
@blade83lee Got it. What is your ng config? You should use `has key` feature in nginx and use the `query_id` as has hey. Then databend query will has load balance otherwise it won't found the correct query server with correct query_id. Here is a nginx conf reference:

```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    log_format main '$http_x_databend_query_id "$time_local" $host "$request_method $request_uri $server_protocol" $status $bytes_sent "$http_referer" "$http_user_agent" $remote_port $upstream_addr $scheme $gzip_ratio $request_length $request_time $ssl_protocol "$upstream_response_time"';
    access_log /opt/homebrew/var/log/nginx/access.log main;
    map $http_x_query_id $backend {
        default backend1;
    }
    upstream backend1 {
        hash $http_x_databend_query_id consistent;
        server localhost:8000;
        server localhost:8009;
    }
    server {
        listen 8085;
        location / {
            proxy_pass http://$backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-DATABEND-QUERY-ID $http_x_databend_query_id;
            proxy_set_header Connection "";
            proxy_http_version 1.1;
        }
    }
}

```
