### ISSUE TITLE
The return value is truncated.

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend-go#95]
![1706868160483](https://github.com/datafuselabs/databend-go/assets/88416508/2d1d1049-b6d9-45d5-992b-3664ec264929)
when the value  has  ‘ ， the return value  is truncated
![企业微信截图_17068684002178](https://github.com/datafuselabs/databend-go/assets/88416508/fb8ee771-d2f4-4d29-856c-8ac7ea1e0ff1)
![1706868479503](https://github.com/datafuselabs/databend-go/assets/88416508/a4f72cc6-8a19-48a0-a10b-aa2487990b1c)

**Comment by hantmac** [comment]
@blade83lee Thanks for your reporting, I will fix it as soon as possible.

**Comment by hantmac** [comment]
@blade83lee BTW, would you like to to show the original `loginfo` value?
